### ISSUE TITLE
PHP 7.2 Compatibility 

### ISSUE THREAD

**Issue by BaileyJM02** [HelioNetworks/HelioLinkExchange#10]
MySQL functions are out of date and need to updated to support 7.2 compatibility. This is to ensure that the development environment is up-to date and that it works correctly on the web server.

\- Bailey

**Comment by wolstech** [comment]
If you're going to worry about replacing the mysql() functions, you might as well add a database wrapper to make future updates/ports to other databases simple.

Here's one I use that's built around the outdated mysql functions: https://www.raxsoft.com/temp/class.db.phps It'd be trivial to retrofit mysqli into it.

Also, I don't recommend targeting 7.2. If this thing ever became official, our non-hosting servers (forum/wiki/website/etc.) offer 5.x (I think 5.4). If we upgrade, it'll be to 5.6 because the classic site and forum do not support 7.x

**Comment by wilcoxm** [comment]
@wolstech agreed.

The PHP version will be needed to upgraded to 5.6 for the wiki too.

So I think 5.6 is a suitable target for now.

Again, I recommend all users to join the discord for discussion. https://discord.io/heliohost

I'm removing this from the alpha milestone, and adding to backlog.

**Comment by BaileyJM02** [comment]
I agree, but it's still not a terrible idea to upgrade. Makes it easier for me to develop and 7.2 is backward compatable with 5.6 as far as I know.

**Comment by wilcoxm** [comment]
@BaileyJM02 maybe, but we should avoid the possibility of breakage.

5.6 is a good target imo, 7.x can come later in the releases.

I can setup a 5.6 server with a subdomain of yours or mine if you wish.

**Comment by BaileyJM02** [comment]
It's fine on my server but I still feel we should update ghe MySQL because it's depreciated anyway, even if don't aim for 7.x.

**Comment by wolstech** [comment]
@BaileyJM02 7.x and 5.x are not fully compatible with each other in either direction actually.

This is the list of stuff that changed/broke: http://php.net/manual/en/migration70.incompatible.php
